services:
  palworld-server:
    image: thijsvanloef/palworld-server-docker:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - PORT=8211
      - PLAYERS=32
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - SERVER_NAME=${SERVER_NAME:-Palworld Server}
      - SERVER_PASSWORD=${SERVER_PASSWORD:-}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      - UPDATE_ON_BOOT=true
    volumes:
      - /opt/palworld/data:/palworld/
    ports:
      - target: 8211
        published: 8211
        protocol: udp
        mode: host
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 25575
        published: 25575
        protocol: tcp
        mode: host
    labels:
      - "com.docker.compose.project=${STACK_NAME:-palworld}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ "node.hostname == gaia" ]
    networks:
      - aether-net

networks:
  aether-net:
    external: true
